[package]
name = "rig-examples"
version = "0.1.0"
edition = "2021"

[workspace]
members = [ "embeddings_demo",
    "ollama_api",
    "ollama_client"
, "tools_demo"]

[dependencies]
rig-core = "0.9.0"
tokio = { version = "1.43.0", features = ["full"] }
