[package]
name = "agent_demo"
version = "0.1.0"
edition = "2021"

[dependencies]
rig-core = { version = "0.9.0", features = ["derive"] }
serde = { version = "1.0.218", features = ["derive"] }
tokio = { version = "1.43.0", features = ["full"] }
