[package]
name = "tools_demo"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.96"
rig-core = "0.9.0"
serde = { version = "1.0.218", features = ["derive"] }
serde_json = "1.0.139"
tokio = { version = "1.43.0", features = ["full"] }
thiserror = "1.0.69"
